name: Update statistics

on:
  workflow_dispatch


jobs:
  calculate:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
    steps:
      - uses: actions/checkout@v2
      - name: Update csv
        run: python3 ./build.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        if: github.ref == 'refs/heads/main'
        with:
          commit_message: Update stats
          commit_author: GitHub Actions <actions@github.com>